title: doutrina.org
description: plataforma de estudos

remote_theme: LeakyAbstractions/pretty-docs

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Build settings
markdown: kramdown
  
