title: 💧 doutrina.org
description: Uma iniciativa para digitalizar as cinco obras básicas da Ciência e Filosofia Espírita.

remote_theme: just-the-docs/just-the-docs

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

markdown: kramdown

