title: 💧 doutrina.org
description: uma plataforma inédita de estudos integrados

repository: sergioSHKLR/pt.doutrina.org

markdown: kramdown

kramdown:
  parse_block_html: false

kramdown:
  input: Kramdown