title: 💧 doutrina.org
description: plataforma de estudos integrados

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jemoji

remote_theme: pages-themes/minimal@v0.2.0
